### ISSUE TITLE
control-monad-free-0.6.1 does not compile with ghc-8.6.1

### ISSUE THREAD

**Issue by peti** [pepeiborra/control-monad-free#6]
~~~
Control/Monad/Free/Zip.hs:24:27: error:
    • Could not deduce (Control.Monad.Fail.MonadFail m)
        arising from a do statement
        with the failable pattern ‘(x : xx)’
      from the context: (Traversable t1, Traversable t2, Monad m)
        bound by the type signature for:
                   unsafeZipWithG :: forall (t1 :: * -> *) (t2 :: * -> *) (m :: *
                                                                                -> *) a b c.
                                     (Traversable t1, Traversable t2, Monad m) =>
                                     (a -> b -> m c) -> t1 a -> t2 b -> m (t2 c)
        at Control/Monad/Free/Zip.hs:22:1-106
      Possible fix:
        add (Control.Monad.Fail.MonadFail m) to the context of
          the type signature for:
            unsafeZipWithG :: forall (t1 :: * -> *) (t2 :: * -> *) (m :: *
                                                                         -> *) a b c.
                              (Traversable t1, Traversable t2, Monad m) =>
                              (a -> b -> m c) -> t1 a -> t2 b -> m (t2 c)
    • In a stmt of a 'do' block: (x : xx) <- get
      In the expression:
        do (x : xx) <- get
           put xx
           lift (f x y)
      In an equation for ‘zipG'’:
          zipG' y
            = do (x : xx) <- get
                 put xx
                 lift (f x y)
   |
24 |        where zipG' y = do (x:xx) <- get
   |                           ^^^^^^^^^^^^^
~~~

**Comment by pepeiborra** [comment]
Thanks for the report, I'll take a look

**Comment by pepeiborra** [comment]
Version 0.6.2 is up in Hackage addressing the 8.6 build
